trainer_config:
  epoches: 600
  batch_size: 128
  lr: 0.0001
  weight_decay: 0.0005
  pre_model_path: ../models/finetuningPlan2/finetuning175all.pt
  save_path: "../models/test/"
  save_logs_name: ../logs/test
  logits_scale: 4.5
  use_cuda: 0

dataset_config:
  data_reat: 0.8                       #数据划分比例
  have_tags: False                      # Ture or False , 是否使用tags
  load_data_type: mongo                  # 数据加载的方式，new or old, 新的数据加载对数据增强做了处理

GCN_model:
  num_layer: 6                       # number of graph conv layers
  emb_dim: 300                          # embedding dimension in graph conv layers
  feat_chang_dim: 512                   #中间变化神经元个数
  feat_dim: 256                        # output feature dimention
  drop_ratio: 0                        # dropout ratio
  pool: mean                            # readout pooling (i.e., mean/max/add)
  gnn_type: gin                        #gnn网络的类型，包含gin与gcn、gat、graphsage
  JK: last
  pre_model: ../models/pre_model/supervised.pth
  version: version1

val_config:
  pre_model: ../models/finetuningPlan2/finetuning175all.pt
  save_logs_name: ../logs/test
  device: cuda:0
  data_reat: 0
  batch_size: 128
  is_wt: False  # 质量约束开关
  is_m: False # 多重性开关
  is_no_activateH: False # 非活泼氢开关
  da: 50
  MongoDB_IP: mongodb://127.0.0.1:27017
  MongoDB_USER: root
  MongoDB_PASSWORD: 123456
